config/routes.rb
Rails.application.routes.draw do



  # get 'users/new'

	get '/home', to: 'static_pages#home'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'
  
  get '/contact', to: 'static_pages#contact'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  get '/users/:id/edit', to: 'users#edit'

  get '/users', to: 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  resources :users
  resources :account_activations, only: [:edit]
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    The
    %a{:href => "http://railstutorial.org/"} Ruby on Rails Tutorial
    by
    %a{:href => "http://www/michaelharlt.com/"} Michael Harlt
  %nav
    %ul
      %li
        = link_to "About",  about_path
      %li
        = link_to "Contact", contact_path
      %li
        %a{:href => "http://news.railstutorial.org/"} News

app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-fixed-top.navbar-inverse
    .container
      = link_to "sample app", home_path, id: "logo"
      %nav
        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to "Home",   home_path
          %li
            = link_to "Help",   help_path
          - if logged_in?
            %li
              = link_to "Users", users_path
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li
                  = link_to "Profile", current_user
                %li
                  = link_to "Setting", "/users/#{current_user.id}/edit"
                %li.devider
                %li
                  = link_to "Log out", logout_path, method: :delete
          - else
            %li
              = link_to "Log in", login_path

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= full_title(yield(:title))
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %script{:crossorigin => "anonymous", :integrity => "sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=", :src => "https://code.jquery.com/jquery-3.3.1.min.js"}
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")
      = yield
      = render 'layouts/footer'